/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_zjf_androidffmpegsample_FFmpeg */

#ifndef _Included_com_example_zjf_androidffmpegsample_FFmpeg
#define _Included_com_example_zjf_androidffmpegsample_FFmpeg
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_zjf_androidffmpegsample_FFmpeg
 * Method:    run
 * Signature: ([Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_example_zjf_androidffmpegsample_FFmpeg_run
  (JNIEnv *, jclass, jobjectArray);

#ifdef __cplusplus
}
#endif
#endif
